---
title: "Analayze sha256 Estimation"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
library(BlockChainPublic)
library(ggplot2)
library(kableExtra)
library(modelsummary)
library(magrittr)
library(foreach)
```

# Load data

```{r}
currency_week_hashrate <- readRDS(file = "../cleaned/currency_week_hashrate.rds")
currency_algo_date <- readRDS(file = "../output/currency_algo_date.rds")
asic_spec_top <- readRDS(file = here::here("output/asic_spec_top.rds"))
epoch_currency <- readRDS(file = here::here("output/epoch_currency_sha256.rds"))
```

# Set constant

```{r}
colour_palette <- 
  c(
    "BTC" = "#F7931A",
    "BCH" = "#0AC18E",
    "BSV" = "#00368C"
  )
```


# Transform data

```{r}
asic_date <-
  asic_spec_top %>%
  dplyr::mutate(date = release) %>%
  dplyr::group_by(model) %>%
  tidyr::complete(model, date = seq(min(date), as.Date("2020-12-31"), by = 1)) %>%
  tidyr::fill(algo, release, hash_rate_spec, power, .direction = "down") %>%
  dplyr::ungroup() %>%
  dplyr::arrange(release)
```


# Analyze data 

## Compare BTC/BCH/BSV {.tabset}

### Daily {.tabset}

```{r}
# make time series 
currency_algo_date %>%
  dplyr::filter(currency %in% c("BTC", "BCH", "BSV")) %>%
  dplyr::mutate(log_winning_rate = log(winning_rate)) %>%
  ggplot(
    aes(
      x = date,
      y = log_winning_rate,
      colour = currency
    )
  ) +
  geom_line() +
  labs(
    x = "Date",
    y = "log(Winning rate)",
    colour = ""
  ) +
  scale_colour_manual(values = colour_palette) +
  theme_classic() +
  theme(
    legend.position = "bottom"
  )
```

```{r}
# make time series 
currency_algo_date %>%
  dplyr::filter(currency %in% c("BTC", "BCH", "BSV")) %>%
  dplyr::mutate(log_hash_rate = log(hash_rate)) %>%
  ggplot(
    aes(
      x = date,
      y = log_hash_rate,
      colour = currency
    )
  ) +
  geom_line() +
  scale_colour_manual(values = colour_palette) +
  labs(
    x = "Date",
    y = "log of Hash rate (H/s)",
    colour = ""
  ) +
  theme_classic() +
  theme(
    legend.position = "bottom"
  )
```


```{r}
# make time series 
currency_algo_date %>%
  dplyr::filter(currency %in% c("BTC", "BCH", "BSV")) %>%
  dplyr::mutate(
    reward_winning_rate = reward_quoteusd * winning_rate,
    log_reward_winning_rate = log(reward_winning_rate)) %>%
  ggplot(
    aes(
      x = date,
      y = log_reward_winning_rate,
      colour = currency
    )
  ) +
  geom_line() +
  scale_colour_manual(values = colour_palette) +
  labs(
    x = "Date",
    y = "Log of reward (USD) x wining rate",
    colour = ""
  ) +
  theme_classic() +
  theme(
    legend.position = "bottom"
  )
```

```{r}
# make time series 
currency_algo_date %>%
  dplyr::filter(currency %in% c("BTC", "BCH", "BSV")) %>%
  dplyr::mutate(
    log_block_time = log(block_time)
  ) %>%
  ggplot(
    aes(
      x = date,
      y = log_block_time,
      colour = currency
    )
  ) +
  geom_line() +
  scale_colour_manual(values = colour_palette) +
  labs(
    x = "Date",
    y = "Log of daily block time s.d. (s)",
    colour = ""
  ) +
  theme_classic() +
  theme(
    legend.position = "bottom"
  )
```

```{r}
# make time series 
currency_algo_date %>%
  dplyr::filter(currency %in% c("BTC", "BCH", "BSV")) %>%
  dplyr::mutate(log_hash_rate_sd = log(hash_rate_sd)) %>%
  ggplot(
    aes(
      x = date,
      y = log_hash_rate_sd,
      colour = currency
    )
  ) +
  geom_line() +
  scale_colour_manual(values = colour_palette) +
  labs(
    x = "Date",
    y = "Log of daily hash rate s.d. (H/s)",
    colour = ""
  ) +
  theme_classic() +
  theme(
    legend.position = "bottom"
  )
```

```{r}
# make time series 
currency_algo_date %>%
  dplyr::filter(currency %in% c("BTC", "BCH", "BSV")) %>%
  dplyr::mutate(
    log_block_time_sd = log(block_time_sd)
  ) %>%
  ggplot(
    aes(
      x = date,
      y = log_block_time_sd,
      colour = currency
    )
  ) +
  geom_line() +
  scale_colour_manual(values = colour_palette) +
  labs(
    x = "Date",
    y = "Log of daily block time s.d. (s)",
    colour = ""
  ) +
  theme_classic() +
  theme(
    legend.position = "bottom"
  )
```


### Daily 14-days moving average {.tabset}

```{r}
# make time series 
winning_rate_figure <-
  currency_algo_date %>%
  dplyr::filter(currency %in% c("BTC", "BCH", "BSV")) %>%
  dplyr::mutate(log_winning_rate = log(winning_rate)) %>%
  ggplot(
    aes(
      x = date,
      y = log_winning_rate,
      colour = currency
    )
  ) +
  tidyquant::geom_ma(
    n = 14,
    linetype = "solid"
    ) +
  labs(
    x = "Date",
    y = "Log of winning rate",
    colour = ""
  ) +
  scale_colour_manual(values = colour_palette) +
  theme_classic() +
  theme(
    legend.position = "bottom",
    legend.text = element_text(size = 8),
    legend.title=element_blank()
  ) + 
  guides(
    color = guide_legend(
      override.aes = list(size = 5)
      )
    )

legend <- ggpubr::get_legend(winning_rate_figure)
winning_rate_figure_legend <- ggpubr::as_ggplot(legend)
        
winning_rate_figure <-
  winning_rate_figure +
  theme(
    legend.position = "none"
    )

plot(winning_rate_figure)
plot(winning_rate_figure_legend)
```

```{r}
# make time series 
hash_rate_figure <-
  currency_algo_date %>%
  dplyr::filter(currency %in% c("BTC", "BCH", "BSV")) %>%
  dplyr::mutate(log_hash_rate = log(hash_rate)) %>%
  ggplot(
    aes(
      x = date,
      y = log_hash_rate,
      colour = currency
    )
  ) +
  tidyquant::geom_ma(
    n = 14,
    linetype = "solid"
    ) +
  scale_colour_manual(values = colour_palette) +
  labs(
    x = "Date",
    y = "Log of hash rate (H/s)",
    colour = ""
  ) +
  theme_classic() +
  theme(
    legend.position = "bottom",
    legend.text = element_text(size = 8),
    legend.title=element_blank()
  ) + 
  guides(
    color = guide_legend(
      override.aes = list(size = 5)
      )
    )

legend <- ggpubr::get_legend(hash_rate_figure)
hash_rate_figure_legend <- ggpubr::as_ggplot(legend)
        
hash_rate_figure <-
  hash_rate_figure +
  theme(
    legend.position = "none"
    )

plot(hash_rate_figure)
plot(hash_rate_figure_legend)
```


```{r}
# make time series 
expected_reward_figure <- 
  currency_algo_date %>%
  dplyr::filter(currency %in% c("BTC", "BCH", "BSV")) %>%
  dplyr::mutate(
    reward_winning_rate = reward_quoteusd * winning_rate,
    log_reward_winning_rate = log(reward_winning_rate)) %>%
  ggplot(
    aes(
      x = date,
      y = log_reward_winning_rate,
      colour = currency
    )
  ) +
  tidyquant::geom_ma(
    n = 14,
    linetype = "solid"
    ) +
  scale_colour_manual(values = colour_palette) +
  labs(
    x = "Date",
    y = "Log of expected reward (USD)",
    colour = ""
  ) +
  theme_classic() +
  theme(
    legend.position = "bottom",
    legend.text = element_text(size = 8),
    legend.title=element_blank()
  ) + 
  guides(
    color = guide_legend(
      override.aes = list(size = 5)
      )
    )

legend <- ggpubr::get_legend(expected_reward_figure)
expected_reward_figure_legend <- ggpubr::as_ggplot(legend)
        
expected_reward_figure <-
  expected_reward_figure +
  theme(
    legend.position = "none"
    )

plot(expected_reward_figure)
plot(expected_reward_figure_legend)

```

```{r}
# make time series 
block_time_figure <-
  currency_algo_date %>%
  dplyr::filter(currency %in% c("BTC", "BCH", "BSV")) %>%
  dplyr::mutate(
    log_block_time = log(block_time)
  ) %>%
  ggplot(
    aes(
      x = date,
      y = log_block_time,
      colour = currency
    )
  ) +
  geom_hline(
    yintercept = log(600),
    linetype = "dotted"
  ) +
  tidyquant::geom_ma(
    n = 14,
    linetype = "solid"
    ) +
  scale_colour_manual(values = colour_palette) +
  labs(
    x = "Date",
    y = "Log of block time (s)",
    colour = ""
  ) +
  theme_classic() +
  theme(
    legend.position = "bottom",
    legend.text = element_text(size = 8),
    legend.title=element_blank()
  ) + 
  guides(
    color = guide_legend(
      override.aes = list(size = 5)
      )
    )

legend <- ggpubr::get_legend(block_time_figure)
block_time_figure_legend <- ggpubr::as_ggplot(legend)
        
block_time_figure <-
  block_time_figure +
  theme(
    legend.position = "none"
    )

plot(block_time_figure)
plot(block_time_figure_legend)
```

```{r}
# make time series 
currency_algo_date %>%
  dplyr::filter(currency %in% c("BTC", "BCH", "BSV")) %>%
  dplyr::mutate(log_hash_rate_sd = log(hash_rate_sd)) %>%
  ggplot(
    aes(
      x = date,
      y = log_hash_rate_sd,
      colour = currency
    )
  ) +
  tidyquant::geom_ma(
    n = 14,
    linetype = "solid"
    ) +
  scale_colour_manual(values = colour_palette) +
  labs(
    x = "Date",
    y = "Log of daily hash rate s.d. (H/s)",
    colour = ""
  ) +
  theme_classic() +
  theme(
    legend.position = "bottom"
  )
```

```{r}
# make time series 
currency_algo_date %>%
  dplyr::filter(currency %in% c("BTC", "BCH", "BSV")) %>%
  dplyr::mutate(
    log_block_time_sd = log(block_time_sd)
  ) %>%
  ggplot(
    aes(
      x = date,
      y = log_block_time_sd,
      colour = currency
    )
  ) +
  tidyquant::geom_ma(
    n = 14,
    linetype = "solid"
    ) +
  scale_colour_manual(values = colour_palette) +
  labs(
    x = "Date",
    y = "Daily average block time (s)",
    colour = ""
  ) +
  theme_classic() +
  theme(
    legend.position = "bottom"
  ) +
  geom_hline(
    yintercept = log(600), linetype = "dotted"
  )
```

```{r}

ggsave(path = "../figuretable/analyze_sha256", 
       filename = "winning_rate.png",
       plot = winning_rate_figure, 
       width = 4, 
       height = 3
       )

ggsave(path = "../figuretable/analyze_sha256", 
       filename = "winning_rate_legend.png",
       plot = winning_rate_figure_legend, 
       width = 2, 
       height = 0.4
       )

ggsave(path = "../figuretable/analyze_sha256", 
       filename = "hash_rate.png",
       plot = hash_rate_figure, 
       width = 4, 
       height = 3
       )

ggsave(path = "../figuretable/analyze_sha256", 
       filename = "hash_rate_legend.png",
       plot = hash_rate_figure_legend, 
       width = 2, 
       height = 0.4
       )

ggsave(path = "../figuretable/analyze_sha256", 
       filename = "expected_reward.png",
       plot = expected_reward_figure, 
       width = 4, 
       height = 3
       )

ggsave(path = "../figuretable/analyze_sha256", 
       filename = "expected_reward_legend.png",
       plot = expected_reward_figure_legend, 
       width = 2, 
       height = 0.4
       )

ggsave(path = "../figuretable/analyze_sha256", 
       filename = "block_time.png",
       plot = block_time_figure, 
       width = 4, 
       height = 3
       )

ggsave(path = "../figuretable/analyze_sha256", 
       filename = "block_time_legend.png",
       plot = block_time_figure_legend, 
       width = 2, 
       height = 0.4
       )
```

### Weekly {.tabset}

```{r}
# make time series 
currency_week_hashrate %>%
  dplyr::filter(currency %in% c("BTC", "BCH", "BSV")) %>%
  dplyr::mutate(log_winning_rate = log(winning_rate)) %>%
  ggplot(
    aes(
      x = week,
      y = log_winning_rate,
      colour = currency
    )
  ) +
  geom_line() +
  labs(
    x = "Week",
    y = "log(Winning rate)",
    colour = ""
  ) +
  scale_colour_manual(values = colour_palette) +
  theme_classic() +
  theme(
    legend.position = "bottom"
  )
```

```{r}
# make time series 
currency_week_hashrate %>%
  dplyr::filter(currency %in% c("BTC", "BCH", "BSV")) %>%
  dplyr::mutate(log_hash_rate = log(hash_rate)) %>%
  ggplot(
    aes(
      x = week,
      y = log_hash_rate,
      colour = currency
    )
  ) +
  geom_line() +
  scale_colour_manual(values = colour_palette) +
  labs(
    x = "Week",
    y = "log of Hash rate (H/s)",
    colour = ""
  ) +
  theme_classic() +
  theme(
    legend.position = "bottom"
  )
```

```{r}
# make time series 
currency_week_hashrate %>%
  dplyr::filter(currency %in% c("BTC", "BCH", "BSV")) %>%
  dplyr::mutate(
    log_block_time = log(block_time)
  ) %>%
  ggplot(
    aes(
      x = week,
      y = log_block_time,
      colour = currency
    )
  ) +
  geom_line() +
  scale_colour_manual(values = colour_palette) +
  labs(
    x = "Week",
    y = "Log of weekly block time s.d. (s)",
    colour = ""
  ) +
  theme_classic() +
  theme(
    legend.position = "bottom"
  )
```

```{r}
# make time series 
currency_week_hashrate %>%
  dplyr::filter(currency %in% c("BTC", "BCH", "BSV")) %>%
  dplyr::mutate(log_hash_rate_sd = log(hash_rate_sd)) %>%
  ggplot(
    aes(
      x = week,
      y = log_hash_rate_sd,
      colour = currency
    )
  ) +
  geom_line() +
  scale_colour_manual(values = colour_palette) +
  labs(
    x = "Week",
    y = "Log of weekly hash rate s.d. (H/s)",
    colour = ""
  ) +
  theme_classic() +
  theme(
    legend.position = "bottom"
  )
```

```{r}
# make time series 
currency_week_hashrate %>%
  dplyr::filter(currency %in% c("BTC", "BCH", "BSV")) %>%
  dplyr::mutate(
    log_block_time_sd = log(block_time_sd)
  ) %>%
  ggplot(
    aes(
      x = week,
      y = log_block_time_sd,
      colour = currency
    )
  ) +
  geom_line() +
  scale_colour_manual(values = colour_palette) +
  labs(
    x = "Week",
    y = "Log of weekly block time s.d. (s)",
    colour = ""
  ) +
  theme_classic() +
  theme(
    legend.position = "bottom"
  )
```
