# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_loglikelihood_arrival_rate_rcpp <- function(theta, winning_rate, epoch_time, generated, x_variable) {
    .Call('_BlockChainPublic_compute_loglikelihood_arrival_rate_rcpp', PACKAGE = 'BlockChainPublic', theta, winning_rate, epoch_time, generated, x_variable)
}

compute_score_arrival_rate_rcpp <- function(theta, winning_rate, epoch_time, generated, x_variable) {
    .Call('_BlockChainPublic_compute_score_arrival_rate_rcpp', PACKAGE = 'BlockChainPublic', theta, winning_rate, epoch_time, generated, x_variable)
}

